In [1]:
%%bash

cd /models && git fetch origin && git checkout origin/tf/transformer-api && pip install .
cd /core && git checkout main && git pull origin main && pip install .
cd /nvtabular && git checkout main && git pull origin main && pip install .
cd /systems && git checkout main && git pull origin main && pip install .
cd /dataloader && git checkout main && git pull origin main && pip install .
pip install matplotlib

From https://github.com/NVIDIA-Merlin/Models
 + 20a40d72...a92bdc24 tf/transformer-api -> origin/tf/transformer-api  (forced update)
any of your branches:

  20a40d72 fix masking of sequence-predict-next transform
  dbd2d9c8 include PR comments
  1e642e87 update example notebook with the new API
  e99e7985 add support of ragged tensor to weight tying
  e87913d1 implement new design of the Transformer API on top of the release-23.02 branch

If you want to keep them by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> 20a40d72

HEAD is now at a92bdc24 adjust sample_weights to targets shape


Processing /models
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'


  Created wheel for merlin-models: filename=merlin_models-0.9.0+116.ga92bdc24-py3-none-any.whl size=374626 sha256=0b09335e9fef4f6221003e7ba9eb2e1e24b4bfdfd433c8211c5ea32aa2856aed
  Stored in directory: /tmp/pip-ephem-wheel-cache-168j85q4/wheels/4d/e8/98/0493db55fff90dc9af123f55a9455b96f7f8166c912a02c8a6
Successfully built merlin-models
  Attempting uninstall: merlin-models
    Found existing installation: merlin-models 0.9.0+114.g20a40d72
    Uninstalling merlin-models-0.9.0+114.g20a40d72:
      Successfully uninstalled merlin-models-0.9.0+114.g20a40d72


Already on 'main'


Your branch is up to date with 'origin/main'.


From https://github.com/NVIDIA-Merlin/core
 * branch              main       -> FETCH_HEAD


Already up to date.
Processing /core
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  Created wheel for merlin-core: filename=merlin_core-0.9.0+54.g29c7587a-py3-none-any.whl size=152409 sha256=cf0f970219f2ae5dcae772911442f0366c3b3400aaac27967ba709e9c9ac1a22
  Stored in directory: /tmp/pip-ephem-wheel-cache-zn63nwq_/wheels/8f/da/8c/c779661788874afaa32fd10abeac6016635956e3bad9940584
Successfully built merlin-core
  Attempting uninstall: merlin-core
    Found existing installation: merlin-core 0.9.0+54.g29c7587a
    Uninstalling merlin-core-0.9.0+54.g29c7587a:
      Successfully uninstalled merlin-core-0.9.0+54.g29c7587a


Already on 'main'


Your branch is up to date with 'origin/main'.


From https://github.com/NVIDIA-Merlin/NVTabular
 * branch              main       -> FETCH_HEAD


Already up to date.
Processing /nvtabular
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'


  Created wheel for nvtabular: filename=nvtabular-1.6.0+42.g9b186ee9-cp38-cp38-linux_x86_64.whl size=258506 sha256=20845f4d83c616304250353b73943fa82e251b9514cbd62b7387b83a6d21efe8
  Stored in directory: /tmp/pip-ephem-wheel-cache-dt3f85gj/wheels/df/bf/c2/9cc2a62fe6da42038c26a9c0c4e25f9767093528b102fa30a2
Successfully built nvtabular
  Attempting uninstall: nvtabular
    Found existing installation: nvtabular 1.6.0+42.g9b186ee9
    Uninstalling nvtabular-1.6.0+42.g9b186ee9:
      Successfully uninstalled nvtabular-1.6.0+42.g9b186ee9


Already on 'main'


Your branch is up to date with 'origin/main'.


From https://github.com/NVIDIA-Merlin/systems
 * branch            main       -> FETCH_HEAD


Already up to date.
Processing /systems
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'


  Created wheel for merlin-systems: filename=merlin_systems-0.7.0+61.g329cba4-py3-none-any.whl size=99480 sha256=c9ed3baf0f65ac381e50f14a63222abcbac99f78a39f4f04bd7e6828a7ed9c16
  Stored in directory: /tmp/pip-ephem-wheel-cache-zfooq_xi/wheels/1f/e9/71/1b0c6295aa7f4b37cb70292d96d87d9f38204674e6531bdda6
Successfully built merlin-systems
  Attempting uninstall: merlin-systems
    Found existing installation: merlin-systems 0.7.0+61.g329cba4
    Uninstalling merlin-systems-0.7.0+61.g329cba4:
      Successfully uninstalled merlin-systems-0.7.0+61.g329cba4


Already on 'main'


Your branch is up to date with 'origin/main'.


From https://github.com/NVIDIA-Merlin/dataloader
 * branch            main       -> FETCH_HEAD


Already up to date.
Processing /dataloader
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'


  Created wheel for merlin-dataloader: filename=merlin_dataloader-0.0.2+41.gdbf8816-py3-none-any.whl size=40852 sha256=60948b9af68c37dfacd1e48a9fdaaad2f9c78225e14116de0d4b643853d839bb
  Stored in directory: /tmp/pip-ephem-wheel-cache-fwvmtvqd/wheels/8c/19/5b/15dc04f5a977f6a7f73ed66c91996a687b1d9e3154a4765536
Successfully built merlin-dataloader
  Attempting uninstall: merlin-dataloader
    Found existing installation: merlin-dataloader 0.0.2+41.gdbf8816
    Uninstalling merlin-dataloader-0.0.2+41.gdbf8816:
      Successfully uninstalled merlin-dataloader-0.0.2+41.gdbf8816


In [1]:
%%bash

rm -rf ecom_dataset
mkdir -p ecom_dataset

pip install gdown
# gdown https://drive.google.com/uc?id=1BvCHc4eXComuNK93bKhRM6cbg9y5p350  # <-- full dataset
gdown https://drive.google.com/uc?id=1NCFZ5ya3zyxPsrmupEoc9UEm4sslAddV
apt-get update -y
apt-get install unzip -y
unzip -d ecom_dataset "rees46_ecom_dataset_small_for_ci.zip"

Downloading...
From: https://drive.google.com/uc?id=1NCFZ5ya3zyxPsrmupEoc9UEm4sslAddV
To: /workspace/rees46_ecom_dataset_small_for_ci.zip
100%|██████████| 43.4M/43.4M [00:08<00:00, 5.42MB/s]


Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Fetched 336 kB in 3s (129 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
unzip is already the newest version (6.0-25ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 83 not upgraded.
Archive:  rees46_ecom_dataset_small_for_ci.zip
   creating: ecom_dataset/0001/
  inflating: ecom_dataset/0001/valid.parquet  
 extracting: ecom_dataset/0001/.zip  
  inflating: ecom_dataset/0001/train.parquet  
  inflating: ecom_dataset/0001/test.parquet  
   creating: ecom_dataset/0002/
  inflating: ecom_dataset/0002/valid.parquet  
  inflating: ecom_dataset/0002/train.pa

In [1]:
import os
os.environ["TF_GPU_ALLOCATOR"]="cuda_malloc_async"
import gc
import numpy as np

import tensorflow as tf

from merlin.schema.tags import Tags
from merlin.io.dataset import Dataset
import merlin.models.tf as mm

2023-03-08 00:23:08.749959: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.8/dist-packages/merlin/dtypes/mappings/torch.py:43: UserWarning: PyTorch dtype mappings did not load successfully due to an error: No module named 'torch'
  warn(f"PyTorch dtype mappings did not load successfully due to an error: {exc.msg}")


2023-03-08 00:23:11.232785: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-08 00:23:11.233226: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-08 00:23:11.233386: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2023-03-08 00:23:11.674938: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow

In [2]:
# this is only temporary, we can align the functionality with the CI script later on

DATA_FOLDER = os.environ.get(
    "DATA_FOLDER", 
    'ecom_dataset/0002'
)

In [3]:
train = Dataset(os.path.join(DATA_FOLDER, "train.parquet"))
valid = Dataset(os.path.join(DATA_FOLDER, "valid.parquet"))

In [4]:
target = 'sess_pid_seq'

In [5]:
train.schema.select_by_name('sess_pid_seq')

[{'name': 'sess_pid_seq', 'tags': set(), 'properties': {'value_count': {'min': 0, 'max': None}}, 'dtype': DType(name='int32', element_type=<ElementType.Int: 'int'>, element_size=32, element_unit=None, signed=True, shape=Shape(dims=(Dimension(min=0, max=None), Dimension(min=0, max=None)))), 'is_list': True, 'is_ragged': True}]

In [6]:
# a couple of hyperparams I took from the CI script in T4Rec

d_model = 192
n_layer = 3
n_head = 16
batch_size = 128
learning_rate = 0.0006667377132554976

In [7]:
mlp_block = mm.MLPBlock(
                [128,d_model],
                activation='relu',
                no_activation_last_layer=True,
            )

In [8]:
from merlin.schema.io.tensorflow_metadata import TensorflowMetadata

schema = TensorflowMetadata.from_proto_text_file(
    './',
    file_name='rees46_schema_modified.pbtxt'
).to_merlin_schema()

/usr/local/lib/python3.8/dist-packages/merlin/schema/tags.py:148: UserWarning: Compound tags like Tags.ITEM_ID have been deprecated and will be removed in a future version. Please use the atomic versions of these tags, like [<Tags.ITEM: 'item'>, <Tags.ID: 'id'>].
  warnings.warn(


In [9]:
train.schema = schema

In [10]:
from merlin.loader.tensorflow import Loader

data = train
dataloader = Loader(data, batch_size=5)
batch = next(dataloader)
print(batch[0])

{'sess_pid_seq': (<tf.Tensor: shape=(45, 1), dtype=int32, numpy=
array([[ 1235],
       [ 4459],
       [27600],
       [ 3457],
       [ 8364],
       [ 7876],
       [ 3457],
       [ 1343],
       [  185],
       [  206],
       [  240],
       [  622],
       [ 7583],
       [    3],
       [    7],
       [    3],
       [ 4458],
       [ 2574],
       [ 5371],
       [ 9683],
       [ 8344],
       [ 1861],
       [ 6581],
       [  303],
       [  709],
       [ 1448],
       [ 1852],
       [ 2730],
       [23721],
       [ 3932],
       [14649],
       [ 6013],
       [ 5585],
       [ 3964],
       [ 1452],
       [ 6581],
       [    2],
       [    7],
       [   12],
       [   24],
       [   51],
       [   72],
       [   54],
       [   23],
       [  326]], dtype=int32)>, <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[ 8],
       [ 5],
       [ 3],
       [20],
       [ 9]], dtype=int32)>), 'sess_ccid_seq': <tensorflow.python.framework.sparse_tensor.SparseTenso

In [ ]:
# import nvtabular as nvt

# ops = ['sess_pid_seq'] >> nvt.ops.Categorify()

# wf = nvt.Workflow(ops)
# train = wf.fit_transform(train)
# valid = wf.transform(valid)

In [12]:
batch = mm.sample_batch(train, batch_size=batch_size, include_targets=False, to_ragged=True)
print(input_block(batch).shape)

/usr/local/lib/python3.8/dist-packages/merlin/schema/tags.py:148: UserWarning: Compound tags like Tags.ITEM_ID have been deprecated and will be removed in a future version. Please use the atomic versions of these tags, like [<Tags.ITEM: 'item'>, <Tags.ID: 'id'>].
  warnings.warn(


(128, None, 192)


In [35]:
train.schema = train.schema.select_by_name('sess_pid_seq')

In [36]:
input_block = mm.InputBlockV2(
    train.schema.select_by_name('sess_pid_seq'),    
    embeddings=mm.Embeddings(
        train.schema.select_by_name('sess_pid_seq'), 
        sequence_combiner=None,
        dim=d_model
        )
)

In [37]:
xlnet_block = mm.XLNetBlock(d_model=d_model, n_head=n_head, n_layer=n_layer)

In [38]:
dense_block = mm.SequentialBlock(
    input_block,
    mlp_block,
    xlnet_block
)

In [39]:
mlp_block2 = mm.MLPBlock(
                [128,d_model],
                activation='relu',
                no_activation_last_layer=True,
            )

In [40]:
prediction_task = mm.CategoricalOutput(
    to_call=input_block["categorical"][target],
)

In [41]:
model_transformer = mm.Model(dense_block, mlp_block2, prediction_task)

In [42]:
optimizer = tf.keras.optimizers.Adam(
    learning_rate=learning_rate,
)

In [43]:
n_epoch = 1

In [44]:
model_transformer.compile(run_eagerly=False, optimizer=optimizer, loss="categorical_crossentropy",
              metrics=mm.TopKMetricsAggregator.default_metrics(top_ks=[4])
             )

In [ ]:
# model_transformer.fit(
#     train,
#     batch_size=batch_size,
#     epochs=n_epoch,
#     pre=mm.SequencePredictRandom(schema=train.schema, target=target, transformer=xlnet_block)
# )

In [46]:
model_transformer.fit(
    train,
    batch_size=batch_size,
    epochs=n_epoch,
    pre=mm.SequencePredictNext(schema=train.schema, target=target, transformer=xlnet_block)
)

/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/indexed_slices.py:444: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradient_tape/model_2/sequential_block_12/xl_net_block_2/prepare_transformer_inputs_4/RaggedToTensor_1/boolean_mask_1/GatherV2:0", shape=(None,), dtype=int32), values=Tensor("gradient_tape/model_2/sequential_block_12/xl_net_block_2/prepare_transformer_inputs_4/RaggedToTensor_1/boolean_mask/GatherV2:0", shape=(None, 192), dtype=float32), dense_shape=Tensor("gradient_tape/model_2/sequential_block_12/xl_net_block_2/prepare_transformer_inputs_4/RaggedToTensor_1/Shape:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(


665/665 [==============================] - 74s 107ms/step - loss: 8.9015 - recall_at_4: 0.0224 - mrr_at_4: 0.0129 - ndcg_at_4: 0.0153 - map_at_4: 0.0129 - precision_at_4: 0.0056 - regularization_loss: 0.0000e+00 - loss_batch: 8.8957


In [47]:
predict_last = mm.SequencePredictLast(schema=valid.schema, target=target, transformer=xlnet_block)

In [49]:
model_transformer.evaluate(
    valid,
    batch_size=batch_size,
    pre=predict_last,
    return_dict=True
)

84/84 [==============================] - 8s 40ms/step - loss: 8.8326 - recall_at_4: 0.0502 - mrr_at_4: 0.0319 - ndcg_at_4: 0.0365 - map_at_4: 0.0319 - precision_at_4: 0.0126 - regularization_loss: 0.0000e+00 - loss_batch: 8.8396


{'loss': 8.832579612731934,
 'recall_at_4': 0.05087455362081528,
 'mrr_at_4': 0.030891483649611473,
 'ndcg_at_4': 0.0359138660132885,
 'map_at_4': 0.030891483649611473,
 'precision_at_4': 0.01271863840520382,
 'regularization_loss': 0.0,
 'loss_batch': 9.142295837402344}